name: 프로젝트 제안하기 - for 멘토(간편한 ver.)
description: 진행할 프로젝트 주제 제안하기
title: "[제안]"
labels: [🙋 제안, 📢 멘티 모집중]
body:
  - type: textarea
    id : textarea1
    attributes:
      label: 어떤 프로젝트를 제안 / 진행하고 싶은가요?
      description: 구체적으로 작성해주시면 문제 파악에 도움이 됩니다.
      placeholder: |
        예시) 웹 프로그래밍 공부하기 (초보자)
    validations:
      required: false

  - type: textarea
    id : textarea2
    attributes:
      label: 프로젝트에 사용되는 프레임워크, 프로그래밍 언어가 무엇인가요?
      description: 구체적으로 작성해주시면 문제 파악에 도움이 됩니다.
      placeholder: |
        예시) Language : 파이썬, Python
        예시) Framework : 장고, Django
    validations:
      required: false

  - type: textarea
    id : textarea3
    attributes:
      label: 프로젝트를 통해서 이루고자 하는 목표는 무엇인가요?
      description: 배우고 싶은 내용, 해결하고 싶은 문제에 대해서 설명해주세요
      placeholder: |
        예시) 웹 프로그래밍 능력 습득
        예시) 객체지향에 대한 이해도 향상, 등등
    validations:
      required: false

  - type: textarea
    id : textarea4
    attributes:
      label: 프로젝트를 통해서 최종적인 목표물은 무엇인가요?
      description: 사진이나 레퍼런스 링크를 첨부해서 최종적으로 만들어보고 싶은 것을 보여주세요!
      placeholder: |
        예시) 이번 프로젝트를 진행함으로써 이 정도의 결과물을 기대합니다(사진 첨부)
    validations:
      required: false

  - type: textarea
    id : textarea5
    attributes:
      label: 어느 정도 수준의 프로그래밍 실력을 요구하는 수준인가요?
      description: 프로젝트 참여자 모두에게 요구되는 수준을 의미합니다
      placeholder: |
        예시) 파이썬으로 for, while, 리스트, 딕셔너리 개념 정도는 아는 정도?
    validations:
      required: false

  - type: textarea
    id : textarea6
    attributes:
      label: 추가로 작성하고 싶은 내용
      description: 한 말씀 하시죠
    validations:
      required: false